Library_system/urls.py
from django.contrib import admin
from django.urls import path, include
from Library_system import views
app_name = 'Library_system'
urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('add_book/', views.add_book, name="add_book"),
    path('books_list/', views.books_list, name="books_list"),
    path('edit_books/', views.edit_books, name="edit_books"),
    path('delete<int:id>', views.delete_book, name="delete"),
    path('update<int:id>', views.update_book, name="update"),
    path('signup', views.user_signup, name="signup"),
    path('logins', views.user_login, name="logins"),
    path('logout', views.user_logout, name="logout"),
]

My_Library_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Library_system.urls',namespace='Library_system')),
]

Library_system/models.py
from django.db import models
from django.utils.timezone import datetime
from django.contrib.auth.models import User
# Create your models here.

class Book(models.Model):
    book_name = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    price = models.PositiveIntegerField()
    category = models.CharField(max_length=255)
    book_num =  models.PositiveIntegerField()
    added_time =models.DateTimeField(auto_now_add=True, blank=True)
    def __str__(self):
        return self.book_name

Library_system/forms.py
from django.forms import ModelForm
from.models import Book
from django import forms

class Bookform(forms.ModelForm):
    class Meta:
        model=Book
        fields='__all__'    


class Updatebookform(forms.ModelForm):
    class Meta:
        model=Book
        fields = ["book_name","author","price","category","book_num"]
        widgets = {
            'book_name': forms.TextInput(attrs={'class': 'form-control', 'id': 'input_box'}),
            'author': forms.TextInput(attrs={'class': 'form-control', 'id': 'input_box'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'id': 'input_box'}),
            'category': forms.TextInput(attrs={'class': 'form-control', 'id': 'input_box'}),
            'book_num': forms.NumberInput(attrs={'class': 'form-control', 'id': 'input_box'}),
        }   


Library_system/views.py
from django.shortcuts import render,redirect
from django.contrib import messages 
from .forms import Bookform,Updatebookform
from .models import Book
from django.contrib.auth  import authenticate,  login, logout
from django.contrib.auth.models import User
# Create your views here.
def home_page(request):
    return render(request, "Home.html")

def add_book(request):
    if request.method=='POST':
        book_form=Bookform(request.POST)
        if book_form.is_valid:
            book_form.save()
            messages.success(request, "New books added....")
            return redirect("Library_system:books_list")
    else:
        book_form=Bookform()
    return render(request,"Add_book.html",{'book_form':book_form})    

def books_list(request):
    books=Book.objects.all()
    return render(request,'Books_list.html',{'books':books})

def edit_books(request):
    edit_books=Book.objects.all()
    return render(request,'Edit_books.html',{'edit_books':edit_books})

def delete_book(request, id):
    db = Book.objects.get(id=id)
    db.delete()
    return redirect("Library_system:edit_books")

def update_book(request,id): 
    book_up = Book.objects.get(id=id)
    if request.method == "POST":
        form = Updatebookform(request.POST or None,instance=book_up)
        if form.is_valid():
            book_up = form.save(commit=False)
            book_up.save()
            messages.success(request, "information has been updated...")
            return redirect("Library_system:edit_books")
    else:
        form = Updatebookform(instance=book_up)
    return render(request, "update_book.html", {'form': form})

def user_signup(request):
    if request.method=="POST":
        # Get the post parameters
        fname=request.POST['fname']
        lname=request.POST['lname']
        username=request.POST['username']
        email=request.POST['email']
        pass1=request.POST['pass1']
        pass2=request.POST['pass2']
        # check for errorneous input
        if not username.isalnum():
            messages.error(request," Username should be contain letters and numbers")
            return redirect("Library_system:signup")

        if (pass1!= pass2):
            messages.error(request," Passwords do not match")
            return redirect("Library_system:signup")
        
        # Create the user
        myuser = User.objects.create_user(username, email, pass1)
        myuser.first_name= fname
        myuser.last_name= lname
        myuser.save()
        messages.success(request, " congratulations! Your account has been created  successfully")
        return redirect("Library_system:home_page")
        
    else:
        return render(request, "signup_page.html")


def user_login(request):
    if request.method=="POST":
        # Get the post parameters
        loginusername=request.POST['loginusername']
        loginpassword=request.POST['loginpassword']

        user=authenticate(username= loginusername, password= loginpassword)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully Logged In")
            return redirect("Library_system:home_page")
        else:
            messages.error(request, "Invalid credentials! Please try again")
            return redirect("Library_system:logins")
    else:
        return render(request, "login_page.html")

def user_logout(request):
    logout(request)
    messages.success(request, "you are successfully logged out")
    return redirect("Library_system:home_page")

templates/Add_book.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}Add Books{% endblock %}
{% block body %}
<div class="form_box">
	<h4 class="text-center">Add New Books Here</h4><br>
	<form method="POST" class="row g-1" action="{% url 'Library_system:add_book' %}">
		{% csrf_token %}
		
          <div class="col-md-6">
				<label for="book_name"><b>Book name</b></label>
			    <input type="text" class="form-control" id="input_box" name="book_name" Required>
          </div><br>
		  
		 
          <div class="col-md-6">
				  <label for="Author"><b>Author</b></label>
			      <input type="text" class="form-control"  id="input_box" name="author" Required>
          </div>
		  
          <div class="col-md-12">
				  <label for="Price"><b>Price</b></label>
			      <input type="number" class="form-control"  id="input_box" name="price" Required>
          </div>
		  
		   
          <div class="col-md-12">
				  <label for="Category"><b>Category</b></label>
			      <input type="text" class="form-control"  id="input_box"  name="category" Required>
          </div>
		   <div class="col-md-12">
				  <label for="No_Books"><b>No. of Books</b></label>
			      <input type="number" class="form-control"  id="input_box"  name="book_num" Required>
          </div>
		 
		  <div class="col-md-12">
				  <button type="submit" id="button" class="btn btn-success btn-block" style="width:100%">Add Book</button>
		  </div>	    
	</form>
</div>
{% endblock %}

templates/Base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
     <style>
		.container{
			width:100%;
			height:auto;
			padding:10px;
		}
		.navbar-dark .navbar-nav .nav-link {
			color: white;
			font-weight:bold;
		}
    .form_box{
			width:65%;
			margin-left:250px;
			padding:6px;
			margin-top:13px;
			border-radius:15px;
			box-shadow:2px 2px 6px 3px grey;
	}
	
	#input_box {
			border-radius:5px;
			background-color:#E3E3E3;
			font-weight:500;
			
	}
	.buttons{
		margin-left:1000px;
	}
	.back_img{
		width: 100%;
		height:87%;
		object-fit:cover;
	}
	.centered {
		position: absolute;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		color:white;
		font-weight:bold;
		font-size:100px;
	  }
	</style>
</head>
<body>
<!-- nav bar of index page  -->
 <nav class="navbar navbar-expand-sm  navbar-dark bg-black" aria-label="Main navigation">
    <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'Library_system:home_page' %}">Home</a>
        </li>
		{% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Library_system:books_list' %}">Books</a>
        </li>
        <li class="nav-item">
          <a class="nav-link nav-link-color" href="{% url 'Library_system:add_book' %}">Add new books</a>
		 </li>
          <li class="nav-item">
          <a class="nav-link nav-link-color" href="{% url 'Library_system:edit_books' %}">Edit books</a>
		 </li>
      </ul>
	  <a class="btn btn-danger btn-block mx-1" href="{% url 'Library_system:logout' %}" role="button">logout</a>
	  {% else %}
	  <div class="buttons">
	  <a class="btn btn-primary btn-block mx-1" href="{% url 'Library_system:signup' %}" role="button">Sign Up</a>
	  <a class="btn btn-primary btn-block mx-1" href="{% url 'Library_system:logins' %}" role="button">Login</a>
	  </div>
	  {% endif %}
    </div>
</nav>
{% for message in messages  %}            
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <strong>Message : </strong> {{ message }} 
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %} 
{% block body %}

{% endblock %}
</body>
</html>

templates/Books_list.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}Books list{% endblock %}
{% block body %}
<div class="list">
<table class="table table-light table-hover table-striped">
  <thead>
    <tr>
      <th scope="col">Book's Name</th>
      <th scope="col">Author</th>
      <th scope="col">Price</th>
	    <th scope="col">Category</th>
	    <th scope="col">No. of books</th>
	    <th scope="col">Added time</th>
    </tr>
  </thead>
  <tbody>
    {% for item in books%}
    <tr>
      <td>{{item.book_name}}</td>
      <td>{{item.author}}</td>
	    <td>{{item.price}}/-</td>
	    <td>{{item.category}}</td>
	    <td>{{item.book_num}}</td>
	    <td>{{item.added_time}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

templates/Edit_books.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}Edit{% endblock %}
{% block body %}
<div class="list">
<table class="table table-light table-hover">
  <thead>
    <tr>
      <th scope="col">Book's Name</th>
      <th scope="col">Author</th>
      <th scope="col">Price</th>
      <th scope="col">Category</th>
      <th scope="col">No. of books</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for item in edit_books%}
    <tr>
      <td>{{item.book_name}}</td>
      <td>{{item.author}}</td>
      <td>{{item.price}}</td>
      <td>{{item.category}}</td>
      <td>{{item.book_num}}</td>
      <td><a class="btn btn-danger btn-sm mx-1" href="/delete{{item.id}}" role="button">Delete</a>
      <a class="btn btn-warning btn-sm mx-1" href="{% url 'Library_system:update' item.id %}" role="button">Update</a>
    </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

templates/Home.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}Home page{% endblock %}
{% block body %}
<img src="{% static 'images/LIB.jpg' %}" class="back_img" alt="Avatar">
{% if user.is_authenticated %}
<div class="centered">Hello,Welcome To Library</div>
{% endif %}
{% endblock %}

templates/login_page.html
{% extends 'Base.html' %}
{% block title %}login page{% endblock %}
{% block body %}
<div class="form_box">
	<h4 class="text-center">Login</h4><br>
	<form  action="/logins" method="POST" class="row g-2">
		{% csrf_token %}
		<div class="col-md-12">
			<label for="username"><b>Username:</b></label>
			<input type="text" class="form-control" id="input_box" placeholder="Enter username" name="loginusername" Required>
		</div><br>
			  
		<div class="col-md-12">
			<label for="password1"><b> Your Password:</b></label>
			<input type="password" class="form-control"  id="input_box" placeholder="Enter password" name="loginpassword" Required>
		</div>
			  
		<div class="col-md-12">
			<button type="submit" class="btn btn-success btn-block"style="width:100%">Login</button>
		</div>  	   
	</form>
</div>
{% endblock %}

templates/signup_page.html
{% extends 'Base.html' %}
{% block title %}Signup page{% endblock %}
{% block body %}
<!--registration form  -->
<div class="form_box">
	<h4 class="text-center">Create Your Account Here</h4><br>
	<form  action="/signup" method="POST" class="row g-1">
	{% csrf_token %}
	
        <div class="col-md-6">
			<label for="username"><b>First Name:</b></label>
			<input type="text" class="form-control" id="input_box" placeholder="Enter Your name" name="fname" Required>
        </div><br>
		  
		<div class="col-md-6">
			<label for="username"><b>Last Name:</b></label>
			<input type="text" class="form-control" id="input_box" placeholder="Enter username" name="lname" Required>
        </div><br>
		  
		<div class="col-md-12">
			<label for="username"><b>Username:</b></label>
			<input type="text" class="form-control" id="input_box" placeholder="Enter Your name" name="username" Required>
        </div><br>
			
	
        <div class="col-md-12">
			<label for="email"><b>Email:</b></label>
			<input type="email" class="form-control"  id="input_box" placeholder="Enter email" name="email" Required>
        </div><br>
			
	
        <div class="col-md-6">
			<label for="password1"><b> Choose a password:</b></label>
			<input type="password" class="form-control"  id="input_box" placeholder="Enter password" name="pass1" Required>
        </div>
 
        <div class="col-md-6">
			<label for="password2"><b>Confirm Password:</b></label>
			<input type="password" class="form-control"  id="input_box" placeholder="confirm password" name="pass2" Required>
        </div>
		  
		<div class="col-md-12">
			<button type="submit" class="btn btn-success btn-block" style="width:100%">Sign up</button>
		</div>
		 
      </form>
</div>
{% endblock %}

templates/update_book.html
{% extends 'Base.html' %}
{% load static %}
{% block title %}Update Books{% endblock %}
{% block body %}
<div class="form_box">
	<h4 class="text-center">Update information of book</h4><br>
	<form method="POST" class="row g-1" enctype="multipart/form-data">
		{% csrf_token %}
		
          <div class="col-md-6">
				<label for="book_name"><b>Book name</b></label>
			    {{form.book_name}}
          </div><br>
		  
		  
          <div class="col-md-6">
				  <label for="Author"><b>Author</b></label>
			      {{form.author}}
          </div>
		  
          <div class="col-md-12">
				  <label for="Price"><b>Price</b></label>
			      {{form.price}}
          </div>
		  
		  
          <div class="col-md-12">
				  <label for="Category"><b>Category</b></label>
				  {{form.category}}
          </div>
		   <div class="col-md-12">
				  <label for="No_Books"><b>No. of Books</b></label>
			      {{form.book_num}}
          </div>
		 
		  <div class="col-md-12">
				  <button type="submit" id="button" class="btn btn-success btn-block" style="width:100%">Update</button>
		  </div>	    
	</form>
</div>

{% endblock %}